apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: pod-memory-cron-wf
  namespace: litmus
spec:
  schedule: "45-59/15 * * * *"
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: argowf-chaos
    serviceAccountName: argo-chaos
    templates:
      - name: argowf-chaos
        steps:
          - - name: run-pod-memory-hog
              template: run-pod-memory-hog
      - name: run-pod-memory-hog
        inputs:
          artifacts:
            - name: run-pod-memory-hog
              path: /tmp/chaosengine-pod-memory-hog.yaml
              raw:
                data: |
                  apiVersion: litmuschaos.io/v1alpha1
                  kind: ChaosEngine
                  metadata:
                    name: orders-pod-memory-hog
                    namespace: litmus
                  spec:
                    annotationCheck: 'false'
                    engineState: 'active'
                    auxiliaryAppInfo: ''
                    appinfo:
                      appns: 'sock-shop'
                      applabel: 'name=orders'
                      appkind: 'deployment'
                    chaosServiceAccount: litmus-admin
                    monitoring: true
                    jobCleanUpPolicy: 'retain'
                    experiments:
                      - name: pod-memory-hog
                        spec:
                          components:
                            experimentImage: "litmuschaos/go-runner:ci"
                            env:
                              - name: TARGET_CONTAINER
                                value: 'orders'
                              - name: MEMORY_CONSUMPTION
                                value: '500'
                              - name: TOTAL_CHAOS_DURATION
                                value: '240' # in seconds
                              - name: CHAOS_KILL_COMMAND
                                value: "kill -9 $(ps afx | grep \"[dd] if /dev/zero\" | awk '{print $1}' | tr '\n' ' ')"
        container:
          image: lachlanevenson/k8s-kubectl
          command: [sh, -c]
          args:
            ["kubectl apply -f /tmp/chaosengine-pod-memory-hog.yaml -n litmus"]