apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: app-sample
    app: app-sample
  name: app-sample
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-sample
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-sample
    spec:
      containers:
        - image: gcr.io/google-samples/node-hello:1.0
          name: app-sample
          resources:
            limits:
              cpu: "500m"
              memory: "200M"
            requests:
              cpu: "200m"
              memory: "100M"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              port: 8080
              path: /health
            initialDelaySeconds: 1
            periodSeconds: 1
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1