{
 "title": "Node and Pod Chaos Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Litmus Chaos Chaos durations interleaved with Node Exporter & Kube-State Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Chaos Experiments",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "CHAOS = TRUE" }
   ],
   "targets": [
    {
     "expr": "litmuschaos_awaited_experiments",
     "legendFormat": "{{chaosresult_name}}"
    }
   ]
  },
  {
   "title": "Total Experiments Run",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(litmuschaos_passed_experiments + litmuschaos_failed_experiments)"
    }
   ]
  },
  {
   "title": "Passed Experiments",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(litmuschaos_passed_experiments)"
    }
   ]
  },
  {
   "title": "Failed Experiments",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(litmuschaos_failed_experiments)"
    }
   ]
  },
  {
   "title": "Queued Experiments",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(litmuschaos_awaited_experiments)"
    }
   ]
  },
  {
   "title": "Chaos - Node - CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "instance:node_cpu_utilisation:rate1m",
     "legendFormat": "\"{{instance}}\""
    }
   ]
  },
  {
   "title": "Chaos - Node - Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "instance:node_memory_utilisation:ratio",
     "legendFormat": "\"{{instance}}\""
    }
   ]
  },
  {
   "title": "Chaos - Node - Network IN/OUT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[1m])) BY (instance)",
     "legendFormat": "\"{{instance}}\" (input)"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[1m])) BY (instance)",
     "legendFormat": "\"{{instance}}\" (output)"
    }
   ]
  },
  {
   "title": "Chaos - Pod - CPU Usage",
   "type": "graph",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"app-sample\"}[5m])) by (pod)",
     "legendFormat": "\"{{pod}}\""
    }
   ]
  },
  {
   "title": "Chaos - Pod - Memory Usage",
   "type": "graph",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container=\"app-sample\"}) by (pod)",
     "legendFormat": "\"{{pod}}\""
    }
   ]
  },
  {
   "title": "Chaos - Pod - Network IN/OUT",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~\"app-sample.+\"}[5m])) by (pod)",
     "legendFormat": "{{pod}} (input)"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~\"app-sample.+\"}[5m])) by (pod)",
     "legendFormat": "{{pod}} (output)"
    }
   ]
  }
 ]
}