apiVersion: v1
kind: Service
metadata:
  annotations:
  name: grafana
  namespace: monitoring
spec:
  ports:
    - nodePort: 31687
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: grafana
  sessionAffinity: None
  type: LoadBalancer
