apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: app-sample-chaos
  namespace: testing
spec:
  # It can be true/false
  annotationCheck: "true"
  # It can be active/stop
  engineState: "active"
  appinfo:
    appns: "testing"
    applabel: "app.kubernetes.io/name=app-sample"
    appkind: "deployment"
  chaosServiceAccount: pod-cpu-hog-sa
  monitoring: true
  # It can be delete/retain
  jobCleanUpPolicy: "retain"
  experiments:
    - name: pod-cpu-hog
      spec:
        components:
          env:
            #number of cpu cores to be consumed
            #verify the resources the app has been launched with
            - name: CPU_CORES
              value: "1"

            - name: TOTAL_CHAOS_DURATION
              value: "60" # in seconds

            - name: PODS_AFFECTED_PERC
              value: "0"
        probe:
          - name: "check-frontend-access-url"
            type: "httpProbe"
            httpProbe/inputs:
              url: "http://app-sample.testing.svc.cluster.local"
              insecureSkipVerify: false
              method:
                get:
                  criteria: ==
                  responseCode: "200"
            mode: "Continuous"
            runProperties:
              probeTimeout: 5
              interval: 5
              retry: 1
              probePollingInterval: 2