apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: catalogue-node-cpu-hog
  namespace: litmus
spec:
  annotationCheck: 'false'
  engineState: 'active'
  auxiliaryAppInfo: ''
  appinfo:
    appns: 'sock-shop'
    applabel: 'name=catalogue'
    appkind: 'deployment'
  chaosServiceAccount: litmus-admin
  monitoring: true
  jobCleanUpPolicy: 'retain'
  experiments:
    - name: node-cpu-hog
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: '240' # in seconds

            - name: NODE_CPU_CORE
              value: '1'