apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: catalogue-pod-cpu-hog
  namespace: litmus
spec:
  annotationCheck: 'false'
  engineState: 'active'
  auxiliaryAppInfo: ''
  appinfo:
    appns: 'sock-shop'
    applabel: 'name=catalogue'
    appkind: 'deployment'
  chaosServiceAccount: litmus-admin
  monitoring: true
  jobCleanUpPolicy: 'retain'
  experiments:
    - name: pod-cpu-hog
      spec:
        components:
          experimentImage: "litmuschaos/go-runner:ci"
          env:
            - name: TARGET_CONTAINER
              value: 'catalogue'

            - name: CPU_CORES
              value: '1'

            - name: TOTAL_CHAOS_DURATION
              value: '240' # in seconds
              
            - name: CHAOS_KILL_COMMAND
              value: "kill -9 $(ps afx | grep \"[md5sum] /dev/zero\" | awk '{print$1}' | tr '\n' ' ')"